### ISSUE TITLE
NetCDF should reject hdf5 files with cycles of symbolic links

### ISSUE THREAD

**Issue by Yurlungur** [Unidata/netcdf-c#320] opened 2016-10-08 13:46 UTC
Hello,

I am contributing to a project which reads files in a large number of formats, including NetCDF and a format built on hdf5 which contains cycles of symbolic links. While working on integrating all these formats, we noticed that we can feed this hdf5 format into the NetCDF API and cause a crash after a long delay.

I would like to suggest adding some heuristics for the hdf5 backend that check whether or not the hdf5 file is in fact a NetCDF file.

(I note that I have only tried this with the Python API.)

Thanks for your time.
### Environment Information
- What platform are you using? (please provide specific distribution/version in summary)
  - [x] Linux
  - [ ] Windows
  - [x] OSX
  - [ ] Other
  - [ ] NA
- 32 and/or 64 bit?
  - [ ] 32-bit
  - [x] 64-bit
- What build system are you using?
  - [ ] autotools (`configure`)
  - [ ] cmake
- Can you provide a sample netCDF file or `C` code to recreate the issue?
  - [x] Yes (please attach to this issue, thank you!)
  - [ ] No
  - [ ] Not at this time
### Steps to reproduce the behavior

The following Python script creates an hdf5 file and then reads it into NetCDF, reproducing the problem.

``` python
import h5py
import numpy as np
f = h5py.File("test.h5","w")
grp=f.create_group('discretizations')
subgrp=grp.create_group('root-disc')
subgrp.create_dataset('disc',data=np.array([0,1,2]))
subsubgrp=subgrp.create_group('first-level')
f['discretizations/root-disc/first-level/parent']=h5py.SoftLink('/discretizations/root-disc')
subsubgrp.create_dataset('disc',data=np.array([0,1,2]))
f.close()

from netCDF4 import Dataset
f=Dataset('test.h5')
```

**Comment by DennisHeimbigner** [comment] 2016-10-08 22:54
Currently, netcdf-c explicitly will not accept and HDF5 file
with group cycles (including symlinks). Testing this on a file
can be somewhat time consuming, so it would best be pushed off
to a tool.

**Comment by Yurlungur** [comment] 2016-10-09 17:48
Thanks for your reply. That makes total sense.

In our case, we use heuristics such as file name or opening the file via a backend to check it looks like a NetCDF file. We just wanted to make sure that you were aware that when faced with such a file the API does not fail gracefully.

**Comment by ngoldbaum** [comment] 2016-10-19 21:46
It may be worth noting that the crash is in the form of a segmentation fault, so this is a possible security/DOS issue.

**Comment by edhartnett** [comment] 2018-08-18 10:32
Can you send me your test file that causes a crash?

**Comment by ngoldbaum** [comment] 2018-08-18 12:33
Is the test script in the issue not sufficient? It’s been a couple years now and we may not be able to track down the original problematic file.

**Comment by edhartnett** [comment] 2018-08-18 23:25
I will come up with a test file, probably tomorrow, and start to explore this issue. I will see if I can reproduce the seg fault.

My first thought for a solution is that I can look at the objinfo and get a unique set of integers that identify a group. If I do that for each group, I should be able to tell that I am in the same group again. In that way, I can detect loops.

We can just error at that point or, if we can figure out what to do that is useful, we can do that. First I will see if I can detect that it is happening, and I would like to ensure that checking it does not impact performance, since I've been working hard to increase performance and reduce what the library does when opening a file. Most files do not have loops, and I don't want to kill performance for everyone checking for loops.

**Comment by ngoldbaum** [comment] 2018-08-20 15:39
On python3.7, using h5py 2.8.0 (not sure what the underlying hdf5 version is), numpy 1.15.0, and netCDF4 1.4.0 running the script @Yurlungur attached in the initial report consumes ~25 GB of RAM on my MacOS 10.13 system. It doesn't crash but it does cause my system to start hitting the page file pretty hard and uses all available RAM.

**Comment by ngoldbaum** [comment] 2018-08-20 15:46
Ah, here we are:

```
Summary of the h5py configuration
---------------------------------

h5py    2.8.0
HDF5    1.10.2
Python  3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.15.0
```

**Comment by edhartnett** [comment] 2018-08-20 16:31
I have tested with both 1.10.1 and 1.10.2, and in both cases it rejects my circularly linked file with NC_EHDFERR. There is no detectable difference in time to execute with or without the statement that attempts to open the file.

I have a test for this which will be added to the code base when it gets merged, so we can detect if this fails in the future, or in other circumstances (i.e. one of the many CI test variants).

**Comment by DennisHeimbigner** [comment] 2018-08-20 17:34
Since detecting cycles is O(V+E),  you are unlikely to see any major performance
hit unless you have a large number of groups.
It occurs to me that we might be able to do incremental cycle detection
as the netcdf library walks part or all of the groups. As each group is read,
we could do the cycle check for just that group. The cost would be the same
but would be spread out over the group read costs.  Since we do not do
lazy group reading, this might not save much.

**Comment by edhartnett** [comment] 2018-08-20 18:00
OK, good point, but the sample given to recreate the problem uses only a couple of groups.

@Yurlungur did the problems only occur on files with lots of groups? Do you have any sample files on which a problem occurred?

**Comment by Yurlungur** [comment] 2018-08-21 23:10
@edhartnett I can try to track down the original problem file for you, but it's been many years since I encountered this problem. The original problem indeed had a large number of groups. However, as @ngoldbaum points out, the test script I provided, which generates a file, caused problems for me. And that file produces only four groups.

**Comment by Yurlungur** [comment] 2018-08-21 23:11
Thank you for looking into this, by the way!

**Closed** 2018-09-06 17:47 UTC
