### ISSUE TITLE
Wrong times reported by "ncdump -t"

### ISSUE THREAD

**Issue by rkouznetsov** [Unidata/netcdf-c#1864] opened 2020-10-14 08:40 UTC
Reproducible with ncdump from 
- netcdf library version 4.7.1 of Aug 31 2019 00:57:34
- netcdf library version 4.7.3 of Jan 23 2020 04:18:16

[timebug.nc.gz](https://github.com/Unidata/netcdf-c/files/5376805/timebug.nc.gz)

`ncdump -t timebug.nc `

reports times starting from midnight, while the first time is at 07Z.
Thank you!

**Comment by lesserwhirls** [comment] 2020-10-14 11:53
I believe this is a duplicate of Unidata/netcdf-c#1417.

**Comment by rkouznetsov** [comment] 2020-10-14 11:58
Thank you! I would guess, it is not a duplicate, although, might be related. That one was caused by undesired conversion of UTC to local time. This one is about ignoring the time specification..

**Comment by lesserwhirls** [comment] 2020-10-14 12:23
`ncdump -t` does not attempt to handle the time zone at all. I think the bug is that when the unit attribute parsing code encounters UTC, it sets the clock time to zero by mistake rather than simply dropping the timezone. See [this comment](https://github.com/Unidata/netcdf-c/issues/1417#issuecomment-580060966) (which appears to have a fix as well). 

And now I see you had been involved in the conversation over on that issue - sorry about the duplicate info here!

I was able to take your example file and 1. drop UTC from the units string and get correct results (e.g. `minutes since 2018-01-03 07:00:00`), and 2. change UTC to MDT (or other string, e.g. `minutes since 2018-01-03 07:00:00 ABCDEFG`) and get correct results. I only see the bug when UTC is used.

**Comment by rkouznetsov** [comment] 2020-10-14 12:55
Thank you!   That report was also from me :), and I got an impression that it been closed already, so did not check it. Sorry. So it is the same bug. So far I have just forced 00Z for all reference times as a workaround...

**Closed** 2020-10-16 17:01 UTC
Labels: type/bug
