### ISSUE TITLE
C lib segfaults when re-writing text attribute as string

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf-c#149] opened 2015-11-10 23:56 UTC
The following python script triggers the error:

    from netCDF4 import Dataset
    import numpy as np
    nc = Dataset('test_att_convert.nc','w')
    nc.foo = np.array('bar','S')
    nc.close()
    nc = Dataset('test_att_convert.nc','a')
    nc.foo = np.array('bar','U')
    nc.close()

The attribute is first written using `nc_put_att_text`, but then is rewritten using `nc_put_att_string`.  On the other hand, this works

    from netCDF4 import Dataset
    import numpy as np
    nc = Dataset('test_att_convert.nc','w')
    nc.foo = np.array(1,np.int8)
    nc.close()
    nc = Dataset('test_att_convert.nc','a')
    nc.foo = np.array(1,np.float64)
    nc.close()

So the C lib is able to handle conversions of numeric types.

**Comment by jswhit** [comment] 2015-11-11 15:41
It is not necessary to close and reopen the file to trigger the segfault, simply writing an attribute as NC_CHAR (with nc_put_att_text) and then re-writing it as NC_STRING (with nc_put_att_string) will do it.

**Comment by jswhit** [comment] 2015-11-11 15:51
Simple C program to trigger the segfault:


    #include <netcdf.h>
    int main() {
       int dataset_id;
       const char *attstring[1] = {"bar"};
       nc_create("test.nc", NC_NETCDF4, &dataset_id);
       nc_put_att_text(dataset_id, NC_GLOBAL, "foo", 3, "bar");
       nc_put_att_string(dataset_id, NC_GLOBAL, "foo", 1, attstring);
       nc_close(dataset_id);
    }

**Comment by WardF** [comment] 2015-11-11 16:39
Hi Jeff,

Thanks for the bug report and the C program; I'm going to take a look at this now.

**Comment by WardF** [comment] 2015-11-11 17:30
Looking at this, it appears the problem isn't in overwriting the attribute string itself, but rather something is happening when `nc_close` is called.  Still debugging, but thought I'd check it out.  It's slower going than usual, as OSX has replaced `gdb` with `lldb`, and there's new syntax to learn.

**Comment by WardF** [comment] 2015-11-11 19:19
The issue has been fixed and the fix is in the current `master` development branch.  Any bugs I've introduced have yet to reveal themselves, as all tests pass.  The issue was a dangling `data` pointer when overwriting the existing attribute.  Closing out the issue.

**Closed by WardF** 2015-11-11 19:19 UTC
Labels: arch/any, area/general, platform/any, status/confirmed, type/bug
