### ISSUE TITLE
CMake build generates incorrect pkgconfig file

### ISSUE THREAD

**Issue by jsharpe** [Unidata/netcdf-c#712] opened 2017-12-04 14:18 UTC
### Summary of Issue
If hdf5 has been installed such that it creates a hdf5 config file with imported targets then the generated config file includes the line:

`Libs: -L${libdir} -lnetcdf -lhdf5::hdf5_hl-shared -lhdf5::hdf5-shared -ldl -lm -lz¬`

which is obviously incorrect for linking hdf5. The hdf5::hdf5-shared and hdf5::hdf5_hl-shared need to have their properties examined to extract the correct libraries to link against as this may include additional transitive dependencies.

**Comment by jsharpe** [comment] 2017-12-04 14:36
Also affects nc-config too.

**Comment by WardF** [comment] 2017-12-04 17:53
Can you provide a little more information; how are you building hdf5, for example? I'm unable to duplicate this on my end, so any additional information you can provide will be very helpful, thanks!

**Comment by jsharpe** [comment] 2017-12-04 18:02
This is how we're building hdf5: https://github.com/zenotech/zCFDSuperBuild/blob/master/Projects/hdf5.cmake

We're using cmake 3.10 and then I'm setting HDF5_DIR to <install>/share/cmake which is where hdf5 puts its cmake config files.

**Comment by WardF** [comment] 2017-12-04 19:41
These strings are being returned by FindHDF5.cmake, it appears; I am working on stripping out the extraneous ::hdf*-shared, etc.

**Comment by WardF** [comment] 2017-12-04 20:13
Addressing this in branch gh712, will merge into master once the travis checks pass.

**Comment by jsharpe** [comment] 2017-12-06 14:27
Whilst your fix sort of resolves this its not the complete fix as you are not pulling in any dependant libraries that hdf5 requires e.g. mpi.

This mailing post provides a solution: https://cmake.org/pipermail/cmake/2016-January/062609.html. Linked is a gist containing a cmake file that grabs all the correct dependencies from the imported targets and thus allows you to correctly pull in : https://gist.github.com/tamaskenez/ef98237fff654c6d28b5. I've no idea how complete this code is or what the minimum version of cmake is that is required to support this but a fully correct solution isn't as simple as your simple search and replace.

**Comment by WardF** [comment] 2017-12-06 16:30
Thanks for the info; I’ll take a look at it.

**Comment by DennisHeimbigner** [comment] 2017-12-06 17:50
IMO, I do not think the netcdf build should be in the business of
trying to figure out the transitive closure of dependencies itself.
Using pkg is ok. A number of the other libraries we use, such as
libcurl and libsz have complicated dependency requirements
and I do think we should get into that quagmire.

**Comment by WardF** [comment] 2017-12-06 18:03
@DennisHeimbigner If cmake has an easy way of capturing that info for use with nc-config, I'm all for it.  You can also use NC_EXTRA_DEPS to specify extra dependencies this way, if you like.  I agree, however; correcting the weird typo on Windows introduced by FindHDF5 was one thing. That was a simple string replace.  But capturing the extensive potential dependencies for this very specific platform/build system is beyond what we'll be able to do.  I'll take a look at the function @jsharpe provided and if we can use it . (or `LINK_INTERFACE_LIBRARIES`, then no problem).  And fwiw, the issue is only in what is dumped into `nc-config`.  If you link against libnetcdf (built as a shared library), the dependencies are/should be captured automatically, and the same with libhdf5, etc.  They just aren't reported.

**Comment by Chrismarsh** [comment] 2018-10-16 16:41
I'm running into this issue (or something related) when building hdf5 + netcdf + netcdf-cxx.

Specifically, if hdf5 was build with cmake, and netcdf is built with cmake, I receive the following error 
`ld cannot find -lhdf5::hdf5_hl-shared` when building netcdf-cxx.

The file `netcdf-c/lib64/cmake/netCDF/netCDFTargets.cmake` produced by building netcdf appears to be the cause of this as it still has the the `hdf5::` and `-shared` text
`INTERFACE_LINK_LIBRARIES "hdf5::hdf5_hl-shared;hdf5::hdf5-shared;/`

**Comment by eli-schwartz** [comment] 2018-10-25 14:28
This has absolutely nothing to do with generating incorrect pkg-config files, since you're not using pkg-config. The `hdf5::` and `-shared` bits are specifically valid in cmake files, and only in cmake files -- they're macros which expand an external virtual target that eventually resolves to a *.so file

In completely unrelated news, you may be hitting this Arch Linux bug: https://bugs.archlinux.org/task/60345
If so, update your system.

The cause is that cmake, as a build system, is utterly broken when it comes to handling dependencies, and its boutique replacement for the pkg-config standard means that if netcdf and hdf5 were both built using cmake, then hdf5 was rebuilt without cmake, the netcdf cmake files are uselessly broken and need to be rebuilt by rebuilding netcdf.

**Comment by Chrismarsh** [comment] 2018-10-25 16:43
@eli-schwartz , thanks for the details. This was one of the few places I could find anything remotely related to that error, and thus the post. I'm not on Arch, but that error is identical to what I'm seeing.

**Comment by Chrismarsh** [comment] 2018-10-25 20:49
@WardF I'm seeing this with HDF5 1.10.4, netcdf ` e0dcb24 #v4.6.1` (as well as head of master as of when I wrote the original reply), and netcdf-cxx4 `50c8b89 # v. 4.3.0`

**Comment by WardF** [comment] 2018-10-26 17:58
Thanks! I'll see what I need to do to accommodate this latest version of HDF5.

**Comment by WardF** [comment] 2019-04-25 21:37
I believe we have this fixed in both pkgconfig and nc-config.

**Closed by WardF** 2019-04-25 21:37 UTC
Labels: status/under review
