### ISSUE TITLE
netcdf-c-4.5.0-rc1 parallel build on 64-bit linux - make -j not working (but make check is)

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#440] opened 2017-07-14 18:13 UTC
### Environment Information

Build of 4.5.0-rc1 with MPICH 3.2, 64-bit linux system with GNU toolchain, using autotools build system.

### Summary of Issue

make -j check fails

### Steps to reproduce the behavior

<pre>
CPPFLAGS='-I/usr/local/zlib-1.2.11_mpich-3.2 -I/usr/local/szip-2.1_mpich-3.2/include -I/usr/local/hdf5-1.10.1_mpich-3.2/include' LDFLAGS='-L/usr/local/zlib-1.2.11_mpich-3.2/lib -L/usr/local/szip-2.1_mpich-3.2/lib -L/usr/local/hdf5-1.10.1_mpich-3.2/lib' CC=mpicc ./configure --enable-parallel-tests --prefix=/usr/local/netcdf-c-4.4.5.0-rc1_mpich-3.2
</pre>

make -j check

It fails for tst_h_dimscales1 and tst_h_rd_cmp. 

I should try and find a fix for this because these are both my tests, I believe! ;-(

Looking on the bright side, the 4.5.0-rc1 build resolves the parallel test issues that existed in the 4.4.1.1 release. So that's very helpful. Not being able to use make -j is a minor inconvenience at worst.

**Comment by WardF** [comment] 2017-07-14 19:14
I'll take a look at this as well; I use `make -j` all over the place in our continuous integration and regression tests, and haven't encountered an error.  That doesn't mean much though, so will investigate this much more closely.

**Comment by WardF** [comment] 2017-07-14 19:16
Correction due to delayed reading comprehension.  I was told early on that our tests do not run in parallel, and must be run serially. Was I misinformed? I would not expect `make -j check` to work, as a number of tests take the output from other tests as input.  I don't know if that's the case for the tests you are seeing failures in, but I had never expected `make check -j` to work.

**Comment by DennisHeimbigner** [comment] 2017-07-14 19:22
I think that is correct. We have, unfortunately, significant dependencies between
tests that are not explicitly recorded in the Makefile. So make -j should not
be expected to work.

**Comment by WardF** [comment] 2017-07-14 19:23
Closing out, will reopen if I learn there's a reason we should expect these to work.  :)

**Closed by WardF** 2017-07-14 19:23 UTC
