### ISSUE TITLE
tst_diskless4 runs forever for version 4.9.0

### ISSUE THREAD

**Issue by bzfbmsch** [Unidata/netcdf-c#2535] opened 2022-10-26 03:40 UTC
Dear support team,
I am trying to build netcdf 4.9.0. This fails, the test

tst_diskless4 500000000 opendiskless

keeps one core busy with 100% "forever".

Compiler: intel 2022 with "-fPIC -O2 -fp-model precise -static-intel"
../netcdf-c-4.9.0/configure --prefix=$NETCDF_ROOT \
            --enable-netcdf-4\
            --enable-cdf5 \
            --enable-dap-long-tests \
            --enable-large-file-tests \
            --with-temp-large=$FAST \
            --enable-mmap \
            --enable-erange-fill \
            --disable-dap-remote-tests \
            --enable-jna

make runs through, make check never ends.

Any suggestion, how to overcome this, would be of great help.

Cheers,
Martin Schmidt

**Comment by WardF** [comment] 2022-10-26 21:48
I'm taking a look to see if I can replicate this; unfortunately I don't have access to the intel compilers, but with any luck I'll be able to get enough information from gcc/clang to see what's going on.

**Comment by WardF** [comment] 2022-10-26 22:36
I was able to replicate this in `v4.9.0`, but it appears to be fixed in the `v4.9.1-rc1` release.  Can you try this release candidate and let us know if the issue is resolved for you?

**Comment by DennisHeimbigner** [comment] 2022-10-27 00:20
Possibly related issues:
* https://github.com/Unidata/netcdf-c/issues/2418
* https://github.com/Unidata/netcdf-c/issues?q=is%3Aissue+is%3Aopen+diskless

**Comment by bzfbmsch** [comment] 2022-10-27 16:02
Thanks for the reply. It was of great help. Two comments:
- I forgot to mention that the issue was not compiler specific.
-  For version 4.9.1-rc1 all checks run through now. So the issue should be resolved.
Many thanks again

**Closed** 2022-10-27 17:32 UTC
