### ISSUE TITLE
Compile errors with 4.4.1 and Visual Studio 11 (2012)

### ISSUE THREAD

**Issue by jmckenna** [Unidata/netcdf-c#304] opened 2016-08-15 14:12 UTC
- using cmake version 3.5.2
- Visual Studio 11 (2012)
- netcdf-c-4.4.1 release (no issues with 4.4.0 release)
- compile errors:

```
>nmake /f Makefile

Microsoft (R) Program Maintenance Utility Version 11.00.50727.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Scanning dependencies of target dispatch
[  1%] Building C object libdispatch/CMakeFiles/dispatch.dir/dparallel.c.obj
dparallel.c
[  2%] Building C object libdispatch/CMakeFiles/dispatch.dir/dcopy.c.obj
dcopy.c
[  3%] Building C object libdispatch/CMakeFiles/dispatch.dir/dfile.c.obj
dfile.c
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\INCLUDE\sys/stat.inl(52) : warning C4028: formal parameter 2 different from declaration
D:\build\mapserver-buildkit-2012\netcdf-c-4.4.1\libdispatch\dfile.c(185) : error C2143: syntax error : missing ';' before 'type'
D:\build\mapserver-buildkit-2012\netcdf-c-4.4.1\libdispatch\dfile.c(186) : error C2065: 'file_len' : undeclared identifier
D:\build\mapserver-buildkit-2012\netcdf-c-4.4.1\libdispatch\dfile.c(192) : error C2065: 'file_len' : undeclared identifier
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by WardF** [comment] 2016-08-16 20:30
Unfortunately, I don't have access to a Visual Studio 11 system anymore to debug this; I will see what I can sort out with Visual Studio 12 or 14, but as those versions don't report an error, it's possible I might not be able to fix this without additional information.

**Comment by emminizer** [comment] 2016-10-17 13:49
I got this error today trying to compile.  The problem is that MSVC 2012 (VC11) is not happy with the variable declaration in the middle of the function.  If the declaration of file_len is moved up several lines, it fixes the compilation error.

**Comment by WardF** [comment] 2016-10-17 15:20
Thank you for the concise description and fix!  This sounds like something I can address "blind" (e.g. I can't test with VC11 myself).  I'm teaching at the Unidata python workshop for the next two days but will address this ASAP.

**Comment by jmckenna** [comment] 2017-01-09 18:22
Can I have an update on this?  Has this fix been added into the distributed source code?

**Comment by WardF** [comment] 2017-01-09 18:38
Thanks for the ping; I've addressed this now in a branch, gh304, and as soon as all the checks pass, I will merge this into `master`.

**Comment by jmckenna** [comment] 2017-01-09 18:59
Thanks.  I was hoping to confirm the changes in the gh304 branch for you, but in fact I get missing symbol errors from the linker, using the gh304 branch.  Darn I'm sorry.

```
   Creating library netcdf.lib and object netcdf.exp
nc_initialize.c.obj : error LNK2019: unresolved external symbol _NC3_initialize referenced in function _nc_initialize
nc_initialize.c.obj : error LNK2019: unresolved external symbol _NC3_finalize referenced in function _nc_finalize
dfile.c.obj : error LNK2019: unresolved external symbol _NC3_dispatch_table referenced in function _NC_create
netcdf.dll : fatal error LNK1120: 3 unresolved externals
```

**Comment by WardF** [comment] 2017-01-09 19:02
My initial fix was not thought out; I just moved stuff without looking at it, and this caused some failures.  It shouldn't cause the failures you've just reported, but would you do a quick pull and try again? I've just pushed the fix for my initial change.

**Comment by jmckenna** [comment] 2017-01-09 19:17
after a clean and then pull, I get the exact same 3 missing symbols error.

**Comment by WardF** [comment] 2017-01-09 20:03
I've added code to accommodate Visual Studio 2012 in `nc3dispatch.h` and `ncdispatch.h`, to fix issues that would explain what you were seeing. Would you give it another try?

**Comment by jmckenna** [comment] 2017-01-09 20:11
sorry to report, exact same 3 missing symbols after clean & pull.

**Comment by WardF** [comment] 2017-01-09 22:42
Ok, I've gone through and looked everywhere I could think and cleaned up a few more places.  Will you give it another try? Sorry for the repeated requests.

**Comment by WardF** [comment] 2017-01-10 18:58
I'm going to merge my fixes and close out this issue; at this point there isn't anything else I can find to change, without further information re: a failure.  Hopefully the last group of changes last night corrected this issue.

**Comment by jmckenna** [comment] 2017-01-10 19:10
Clean & pulled again, with exact same 3 errors.

**Comment by jmckenna** [comment] 2017-01-10 19:10
It is of course ironic how I awaited since August for your feedback, but you could not await my update overnight :)

Anyway, I am sorry for this noise.

**Comment by jmckenna** [comment] 2017-01-10 19:16
To install this compiler locally, it is very easy (I have many versions of MSVC on the same machine).  Here is the download link: https://www.microsoft.com/en-ca/download/details.aspx?id=34673

**Comment by jmckenna** [comment] 2017-01-10 19:18
Failing that, there should be a note in the documentation that Visual Studio 2012 is no longer supported.   Ok, sorry for this long-open ticket.   Thanks for your time and efforts.  Ciao.  -jeff

**Comment by DennisHeimbigner** [comment] 2017-01-10 20:08
I am curious about this, so bear with me.
Since NC3_initialize, NC3_finalize, and NC3_dispatch_table are not being located,
it should be the case that the corresponding NC4 references e.g. NC4_dispatch_table
cannot be found either. Are you building with netcdf-4 enabled? Are you getting
corresponding NC4 errors?

**Comment by jmckenna** [comment] 2017-01-10 20:14
Thanks, sorry for my poor tone, and thanks for understanding.

I agree, it could be a unique setting in my cmake command.  I am building with netcdf-4 disabled, here is the command:

cmake -G "NMake Makefiles" .. 
 -DCMAKE_INSTALL_PREFIX=D:\build\mapserver-buildkit-2012\netcdf-c-git-gh304\build\release
 -DBUILD_SHARED_LIBS=ON 
 -DENABLE_NETCDF_4=OFF 
 -DENABLE_DAP=ON 
 -DBUILD_UTILITIES=OFF 
 -DENABLE_TESTS=OFF 
 -DUSE_HDF5=OFF 
 -DCMAKE_BUILD_TYPE=RELEASE 
 -DZLIB_INCLUDE_DIR="%ZLIBDIR%\include" 
 -DZLIB_INCLUDE_DIR="%ZLIBDIR%" 
 -DZLIB_LIBRARY="%ZLIBDIR%\contrib\vstudio\vc11\x86\ZlibDllRelease\zlibwapi.lib" 
 -DCURL_INCLUDE_DIR="%CURLDIR%\include" -DCURL_LIBRARY="%CURLDIR%\lib\libcurl_imp.lib"

**Comment by jmckenna** [comment] 2017-01-10 20:15
Oh, I am not receiving any other errors than the NC3 errors initially reported.

**Comment by DennisHeimbigner** [comment] 2017-01-10 20:22
Ok, next, do you enough info from cmake or your build directory
to see if e.g. libsrc/nc3dispatch.o is being included in the linking process?

**Comment by DennisHeimbigner** [comment] 2017-01-10 20:27
I am looking at include/ncdispatch.h and I see the following difference.
NCD_EXTERNL NC_Dispatch* NC3_dispatch_table;
vs 
extern NC_Dispatch* NC3_dispatch_table;

Similarly for NC3_initialize and NC3_finalize.

Try as an experiment to make the declarations ofr NC3_... the same
as for NC4_...
If you use 'extern' then II would expect NC3_dispatch_table to be found.
If you use 'NCD_EXTERNL' then II would expect NC4_dispatch_table to start failing.

**Comment by jmckenna** [comment] 2017-01-10 20:31
I see, on lines 130-132.  Will try now...

**Comment by jmckenna** [comment] 2017-01-10 20:49
Darn still the same errors (this seemed like it should work).

```
nc_initialize.c.obj : error LNK2019: unresolved external symbol _NC3_initialize referenced in function _nc_initialize
nc_initialize.c.obj : error LNK2019: unresolved external symbol _NC3_finalize referenced in function _nc_finalize
dfile.c.obj : error LNK2019: unresolved external symbol _NC3_dispatch_table referenced in function _NC_create
netcdf.dll : fatal error LNK1120: 3 unresolved externals
```

**Comment by jmckenna** [comment] 2017-01-10 20:53
There is no file named nc3dispatch.obj in the build directory either.

**Comment by jmckenna** [comment] 2017-01-10 20:58
I notice in my 4.4.0 build directory, the file nc3dispatch.c.obj is generated (but not in the gh304 branch).

**Comment by WardF** [comment] 2017-01-10 20:59
I've reopened; no worries about the tone. It wasn't closed because I hadn't heard from you, it was closed because there wasn't a 'next step' on my end.  Thanks for providing the link to the VS11 install, I've reopened this while I try to debug on my end.  I'm updating my Windows VM and then will install VS11 and try to recreate this.  

Regarding the NCD_EXTERNL; unfortunately, @DennisHeimbigner , Visual Studio (until recently) wouldn't work with `extern`; you had to specify whether you were importing/exporting symbols. The symbols mentioned above weren't being set with NCD_EXTERNL, that change is part of the fix I made.  It's why I'm confused why this is still occurring.  I'll get VS11 installed and see if I can recreate this.

**Comment by DennisHeimbigner** [comment] 2017-01-10 21:19
Ok, then judging from the most recent comments, I would
expect that there is some other error occurring during the compilation of
libsrc so that it is not completing, but the build continues. Hence the
missing items. So, you need to make cmake run as verbosely as possible,,
look at the compilation of libsrc and see if there is some other fatal error
occurring.

**Comment by WardF** [comment] 2017-01-10 21:24
This is possible; there were a couple of errors I had to fix for Visual Studio 10 (which I did have) to compile.

**Comment by WardF** [comment] 2017-01-10 23:56
Ok, I have something that works with Visual Studio 2012 now; can you confirm it works on your end? It's in the `master` branch.

**Comment by jmckenna** [comment] 2017-01-11 15:21
Same exact 3 errors with today's master branch.

**Comment by jmckenna** [comment] 2017-01-11 15:24
Similar as before: I notice in my 4.4.0 build directory, the file nc3dispatch.c.obj is generated (but not in the master branch).

**Comment by WardF** [comment] 2017-01-11 17:32
Ok.  I'm starting to wonder if this is environmental, as I can no longer recreate the issue with visual studio 12.  Can you give it a try in a completely new build directory?  Also, can you build the 'Experimental' target so that the results are uploaded to our web dashboard where I can investigate them?  You can build this from visual studio, I'm certain, *or* from the command line you can run:

    cmake --build . --config Release --target Experimental

(after running the initial cmake command, of course).

**Comment by jmckenna** [comment] 2017-01-11 17:52
No problem.  (I delete my build directory each time, by the way).  More shortly...

**Comment by jmckenna** [comment] 2017-01-11 17:56
```
Submit files (using http)
   Using HTTP submit method
   Drop site:http://
   Submit failed, waiting 5 seconds...
   Retry submission: Attempt 1 of 3
   Submit failed, waiting 5 seconds...
   Retry submission: Attempt 2 of 3
   Submit failed, waiting 5 seconds...
   Retry submission: Attempt 3 of 3
   Error when uploading file: D:/build/mapserver-buildkit-2012/netcdf-c-git-master/build/Testing/20170111-1755/Build.xml
   Error message was: Couldn't resolve host 'http'
```

**Comment by jmckenna** [comment] 2017-01-11 17:59
attached the build output: [build.zip](https://github.com/Unidata/netcdf-c/files/699672/build.zip)

**Comment by WardF** [comment] 2017-01-11 18:43
This is very odd.  The CMakeLists.txt file you're working from should set the appropriate values (`NC_CTEST_SITE`, `NC_CTEST_DROP_SITE`, `NC_CTEST_DROP_LOC_PREFIX`, etc) assuming that you're building with tests enabled; I see you don't actually say that that is what you're doing, so perhaps an incorrect assumption on my part.  If you aren't running with tests enabled, can you re-build, with tests enabled, and then try the `experimental` target again?

**Comment by jmckenna** [comment] 2017-01-11 18:45
my full cmake command is above (I assumed you were using my exact command in your local tests).  As noted, it includes: -DENABLE_TESTS=OFF

**Comment by jmckenna** [comment] 2017-01-11 18:46
Ok trying with -DENABLE_TESTS=ON   now....

**Comment by WardF** [comment] 2017-01-11 18:47
Ok, I had scanned to the top of the message thread and didn't see your
command there; sorry about that.

**Comment by jmckenna** [comment] 2017-01-11 18:55
"Submission successful"

**Comment by WardF** [comment] 2017-01-11 19:06
ah! Thank you, I think I see the error.  Let me check a couple things to make sure I'm on the right track.  If you're interested, you can view the results at:

* [http://my.cdash.org/index.php?project=netcdf-c](http://my.cdash.org/index.php?project=netcdf-c)  

Only the build failure is of interest; the tests failed as one would expect.  

My suspicion is that you do not have `m4` installed on your system, which explains why the generated file `putget.c` is not being found.  You can see this detail at:

* [http://my.cdash.org/viewConfigure.php?buildid=1114566](http://my.cdash.org/viewConfigure.php?buildid=1114566)

We include the generated `.c` files in releases, but not in the development branch.  The solution may be as easy as installing `m4`, but I don't want to say that's what needs to be done until I've looked into it a bit more.  I have m4 as a side-effect of other packages I've installed, not because I set out to install it.

**Comment by jmckenna** [comment] 2017-01-11 19:14
That dashboard is super cool!  Glad it was helpful.

You're correct on `m4` missing on my build system.  Let me know what you recommend for my case...

**Comment by WardF** [comment] 2017-01-11 21:37
Ok, I think your best bet will be to download and install the `m4` utility on your system, ensuring that it is on the system path so that it can be executed by cmake.  You can find the `m4` website here:

* [https://www.gnu.org/software/m4/m4.html](https://www.gnu.org/software/m4/m4.html) Once that is installed, try your build again and let me know if you encounter additional failures. Thanks!

**Comment by DennisHeimbigner** [comment] 2017-01-11 21:48
So I can be clear, this m4 issue is when building from github, not when building
from our distributions, correct?

**Comment by WardF** [comment] 2017-01-11 22:01
Correct; it gives an indication that there was a problem, but it is not obvious that the lack of `m4` was the issue.  We adhere to the general rule of thumb of "don't commit generated files" for the development branches, but when there is a release, I ensure that all of the generated files are included as part of the distribution.  The assumption I've made is that if you are working with the development branch, you are likely a developer, and if you are a developer you will either have `m4`, or be up for installing it in your environment (as it is a common enough tool).  

There is no such assumption for end users who are installing releases, so I make sure they have the files they need :).  At least, I try to.

**Comment by jmckenna** [comment] 2017-01-11 22:28
Bingo, works!  It was indeed the missing `m4.exe` in my path.  In my case, I already had MSYS/MING32 on the system, so all I needed to do was make sure that its `bin` directory was included in my PATH with
```
  set PATH=%PATH%;C:\MinGW\msys\1.0\bin
```

`netcdf.dll` compiles now with `master` and Visual Studio 2012.  Thank you @WardF for all this effort!  I've made notes on this requirement of m4, for when I need master or other branches again.  Let me know if I can help by adding this note anywhere else, publicly, so other developers can find it.

**Closed** 2017-01-12 18:03 UTC
Labels: resolution/patch welcome, status/can't duplicate, status/more information needed, status/under review
