### ISSUE TITLE
ncdump crashes on this file

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf-c#481] opened 2017-09-08 15:16 UTC
A netcdf4-python user reported that opening this file crashes the python interpreter.  Simply running ncdump on it causes a crash.  On my mac:

```
jwhitaker% ncdump s1a-wv2-ocn-vv-20151204t000217-20151204t000219-008884-00cb47-044.nc
Assertion failed: (type == NC_BYTE || type == NC_CHAR || type == NC_SHORT || type == NC_INT || type == NC_FLOAT || type == NC_DOUBLE || type == NC_UBYTE || type == NC_USHORT || type == NC_UINT || type == NC_INT64 || type == NC_UINT64 || type == NC_STRING), function v1h_get_nc_type, file v1hpg.c, line 211.
Abort
```

**Comment by jswhit** [comment] 2017-09-08 15:17
[ncFile.zip](https://github.com/Unidata/netcdf-c/files/1288296/ncFile.zip)

**Comment by DennisHeimbigner** [comment] 2017-09-08 19:55
This is a known problem and there is a fix for it. But unfortunately,
we are backed up in merging pull requests, so it has not made it
into master or the 4.5 rc. I am attaching the file that needs to change.
(actually a zip containing that file)
[d4rc.zip](https://github.com/Unidata/netcdf-c/files/1288850/d4rc.zip)
It should be compatible with master branch and all the v4.5 rc branches.

**Comment by WardF** [comment] 2017-09-08 19:57
Oh! I take back what I said about the issue.  Dennis, was there an open
issue (or closed) related to this I can reference?

**Comment by DennisHeimbigner** [comment] 2017-09-09 00:41
Fixed by pr https://github.com/Unidata/netcdf-c/pull/482
and now merged into branch v4.5-release-candidate

**Comment by stefanomattia** [comment] 2017-12-19 10:51
Hi, I seem to be experiencing the same kind of problem opening my netCDF4 files. Everything was working fine until yesterday. Then I updated my python netCDF4 installation to 1.3.1 (py36_2 conda-forge) and now python crashes every time I try to open a product.

Whenever I try to open my products within python, the interpreter crashes with an ```Abort trap: 6``` error. Same happens when trying to use ```ncdump``` on them.

```
$ ncdump S5P_OFFL_L2__NO2____20171129T010127_20171129T024256_00662_01_001107_20171202T195637.nc
Abort trap: 6
```

I downloaded the zip file from the original poster and it crashes too, giving some more information about failed asserts:

```
$ ncdump s1a-wv2-ocn-vv-20151204t000217-20151204t000219-008884-00cb47-044.nc
Assertion failed: (type == NC_BYTE || type == NC_CHAR || type == NC_SHORT || type == NC_INT || type == NC_FLOAT || type == NC_DOUBLE || type == NC_UBYTE || type == NC_USHORT || type == NC_UINT || type == NC_INT64 || type == NC_UINT64 || type == NC_STRING), function v1h_get_nc_type, file /Users/travis/miniconda3/conda-bld/libnetcdf_1510201535320/work/netcdf-c-4.5.0/libsrc/v1hpg.c, line 212.
Abort trap: 6
```

The ```ncdump``` executable comes from the Anaconda distribution, which I just reinstalled from scratch hoping it was just a dependency problem.

```netcdf library version 4.5.0 of Nov  9 2017 04:27:50 $```

As an additional information, in the meantime I also updated the Command Line Tools (macOS High Sierra version 10.13) for Xcode, not quite sure if that had an impact too, as I started experiencing this problem before this upgrade, and just after upgrading the python netCDF4 package to 1.3.1

**Comment by stefanomattia** [comment] 2017-12-19 14:13
2nd update.

Opening the same products on Linux, with either libnetcdf 4.1.1.1 or libnetcdf 4.5.0 (and of course 4.1.1) does not result in any crash: the products are perfectly readable.

The issue then seems to be only affecting OS X.

Would you know whom I should report this issue to?

**Comment by DennisHeimbigner** [comment] 2017-12-19 20:47
Did you try applying the fix'd file above to see if it fixes your problem?

**Comment by stefanomattia** [comment] 2017-12-19 21:17
I haven't yet, but I suspect it is a conda packaging issue, as the problem doesn't show up with the same environment on Linux. I opened an issue with anaconda, I'll let you know.

**Comment by stefanomattia** [comment] 2017-12-21 10:03
It turned out to be a [buffer overrun](https://github.com/Unidata/netcdf-c/pull/729) bug, which was caught on OS X because the netCDF4 package was built with the ```-fstack-protector-strong``` CFLAG.

**Comment by DennisHeimbigner** [comment] 2017-12-21 17:21
Will you either setup a pull request or send me the fix?

**Comment by stefanomattia** [comment] 2017-12-21 17:53
I believe it's been taken care of in [issue 729](https://github.com/Unidata/netcdf-c/pull/729).

**Comment by WardF** [comment] 2017-12-21 20:27
I'm still seeing this with both the fix for #729 and #482 merged in.  Investigating further.

**Comment by WardF** [comment] 2017-12-21 20:43
Also seeing this in linux currently, so investigating further.

**Comment by DennisHeimbigner** [comment] 2017-12-21 21:15
This appears to be a different problem than the previous one. The previous
one was reference thru a NULL pointer. This is different.,
I tried it with valgrind, but valgrind failed. If anyone has abetter
memory checker any result would be appreciated.

**Comment by WardF** [comment] 2017-12-21 21:17
The issue is `type=512` value failing an assert in v1phg.c:201.  Are we certain this is a valid file? I'm proceeding with the assumption that it is.

**Comment by DennisHeimbigner** [comment] 2017-12-21 21:22
Is there a known older version of netcdf that does not fail? If so, we might be able
to look at the differences in v1hpg.c to see if there is anything suspicious.

**Comment by WardF** [comment] 2017-12-21 21:24
I'm stepping back through now, back to v4.3.1 (under test) and have not yet found a version that works.

**Comment by WardF** [comment] 2017-12-21 21:27
I've been testing on OSX, about to try linux since it has been reported that this worked on linux (although I was seeing failures on my linux vm locally).  Still fails as far back as v4.3.1.  Going back much further won't be possible on OSX, as there was an API change at some point that broke compiling on OSX for older versions.

**Comment by WardF** [comment] 2017-12-21 21:29
(Note I am testing C library/ncdump, not the python interface).

**Comment by edhartnett** [comment] 2017-12-21 21:37
Does h5dump work on the file?

**Comment by WardF** [comment] 2017-12-21 21:39
No it doesn't.

**Comment by WardF** [comment] 2017-12-21 21:40
This suggests it is a corrupt file, but if @jswhit can provide us with any provenance info, we can try to diagnose it further.  Otherwise I'll re-close this issue and move on.

**Comment by DennisHeimbigner** [comment] 2017-12-21 22:11
If it is corrupted, then it is important to know what software produced this netcdf-3 file.

**Comment by DennisHeimbigner** [comment] 2017-12-21 22:14
BTW, the file I am testing is
s1a-wv2-ocn-vv-20151204t000217-20151204t000219-008884-00cb47-044.nc
and looking at its magic number it is a CDF version 1 file.
So I would not expect h5dump to work.

**Comment by edhartnett** [comment] 2017-12-21 22:29
OK sorry I assumed a netCDF-4 file....

**Comment by wkliao** [comment] 2017-12-21 23:28
I ran [ncvalidator](http://cucis.ece.northwestern.edu/projects/PnetCDF/doc/pnetcdf-c/ncvalidator.html) to validate the file header and got the following error messages, which indicates the first dimension's ID of variable "owiWl" is invalid. The ID value is larger than the number of dimensions defined in the file, which is only 11 in the file.
```
Error @ [0x000030f8]:
	Variable "owiWl": dimid[0]=102 is larger than the number of dimensions defined in file (11)
	(Error NC_EBADDIM at line 1602 in file ../../../../parallel-netcdf-1.9.0/src/utils/ncvalidator/ncvalidator.c)
File "s1a-wv2-ocn-vv-20151204t000217-20151204t000219-008884-00cb47-044.nc" fails to conform with CDF file format specifications
```

**Comment by DennisHeimbigner** [comment] 2017-12-22 02:39
Thanks. I forgot about your ncvalidator. So now the question is: how was
this file constructed?

**Comment by WardF** [comment] 2017-12-22 23:11
I am going to tentatively close this, since it's not an issue we will need to address, but closing it will also not prevent further comments.

**Closed by WardF** 2017-12-22 23:11 UTC

**Comment by DennisHeimbigner** [comment] 2017-12-22 23:29
One last note; ncdump should not crash, even if the file is illegal/corrupt.

**Comment by WardF** [comment] 2017-12-22 23:43
It 'crashes' as a result of an assert statement, so we can rewrite that as need be.

**Comment by DennisHeimbigner** [comment] 2017-12-23 02:20
True, we can fix the proximate cause, but ncvalidate indicates
a different root cause that would be nice to catch instead.

**Comment by edhartnett** [comment] 2017-12-23 02:50
Maybe ncdump should incorporate some or all of the features/code of ncvalidate? When a file can't be ncdumped, then some useful information can be given as to why.

If ncvalidate can figure out what is wrong, then why can't ncdump?

Just a thought for the future...

**Comment by WardF** [comment] 2017-12-24 03:51
Perhaps at some point but with our current constraints there’s no reason to reinvent this particular wheel :).
