### ISSUE TITLE
nc_open crash on a corrupted SOFA file 

### ISSUE THREAD

**Issue by krisfed** [Unidata/netcdf-c#2735] opened 2023-08-11 11:08 UTC
Hello netCDF folks!

My apologies, but it seems we have run into another crash on a corrupted file. This time it is a SOFA file (which are based on netCDF-4). See [corrupted.sofa.zip](https://github.com/Unidata/netcdf-c/files/12320728/corrupted.sofa.zip) attached.

The crash only happens when some memory checking environment variables are set and some repeating of `nc_open` call maybe required to reproduce. Here is the crash on unix:

```
% setenv MALLOC_CHECK_ 3
% ./a.out

Loop #: 0
Error code: -101 from nc_open
NetCDF: HDF error

Error code: -33 from nc_close
NetCDF: Not a valid ID


Loop #: 1
free(): invalid pointer
Abort
```
and on mac:

```
$ export MallocScribble=1
$ ./a.out 
a.out(35766,0x7ff85d185340) malloc: enabling scribbling to detect mods to free blocks

Loop #: 0
a.out(35766,0x7ff85d185340) malloc: *** error for object 0xaaaaaaaaaaaaaaaa: pointer being freed was not allocated
a.out(35766,0x7ff85d185340) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
We are seeing this crash on Windows as well.

Here is the code to reproduce the issue:

```C++
#include <iostream>
#include "netcdf.h"

void checkErrorCode(int status, const char* message){
    if (status != NC_NOERR){
        std::cout << "Error code: " << status << " from " << message << std::endl;
        std::cout << nc_strerror(status) << std::endl << std::endl;
    }
}

int main(int argc, const char * argv[]) {
    int ncid;
    int retval;
    
    for (int i = 0; i<10; i++)
    {
        std::cout <<  std::endl << "Loop #: " << i << std::endl;
        
        // open file
        retval = nc_open("corrupted.sofa", NC_NOWRITE, &ncid);
        checkErrorCode(retval, "nc_open");
        
        // close file
        retval = nc_close(ncid);
        checkErrorCode(retval, "nc_close");

    }
    
    return retval;
}

```

We are using netCDF-C v4.9.1.

Again, I think it is understandable that a corrupted file can cause a crash. So thanks a lot for taking a look!

Kris

**Comment by DennisHeimbigner** [comment] 2023-08-17 23:00
I checked this out on Ubuntu Linux and Windows using our current master.
It fails with a return code of NC_EHDF5 rather than crashing.
So apparently this accidentally fixed by some other change.

**Comment by krisfed** [comment] 2023-08-18 17:50
Thank you for taking a look, Dennis!

To clarify, you are not seeing a crash on Linux even when running `nc_open` on a loop after setting `setenv MALLOC_CHECK_ 3` (as above)? What about setting `setenv MALLOC_PERTURB_ 204`?

**Comment by DennisHeimbigner** [comment] 2023-08-19 01:05
What are you using for memory checking: -fsanitize or valgrind or what?

**Comment by krisfed** [comment] 2023-08-22 10:51
Hi Dennis,

To trigger the crash it was enough to set MALLOC_CHECK_ to 3.
I have not tried running the repro code through valgrind, etc.

**Comment by WardF** [comment] 2023-08-22 17:08
I'm able to reproduce this, but I'm not sure there's not much we can do about it.  Without memory-debugging variables enabled  (thanks for the tip about `MallocScribble`, I didn't know about that one), libhdf5 returns an error which we catch and report. Yay!

***With*** memory-debugging variables enabled (be it `MALLOC_CHECK_`, `MallocScribble`, or compiling with `-fsanitize=address -fno-omit-frame-pointer`), the memory violation results in an immediate crash.  But because the crash happens in `libhdf5`, there's no way for us to address this without wiring in a signal handler into libnetcdf; this is the sort of thing that would typically be added in the layer above `libnetcdf`, by whatever software is using it.  

I guess the TLDR here is that this issue needs to be reported to the HDF team.

**Comment by krisfed** [comment] 2023-08-23 10:19
Thank you @WardF ! I have reached out to The HDF Group about this issue. If needed, would you be able to help with narrowing down how to reproduce the issue with HDF5 code, outside of netCDF?

**Comment by WardF** [comment] 2023-08-23 19:13
I'd be happy to help as best I can, absolutely!

**Comment by WardF** [comment] 2023-08-23 19:16
It occurs to me that a good test might be to set the same Malloc-related variables which invoke an immediate exception, build libhdf5, and run `make check`. It doesn't guarantee an exception with the same root cause, but if their test suite tests the related functionality, it should catch it.

**Closed** 2023-08-24 16:15 UTC
