### ISSUE TITLE
ncdump 4.4.0-rc1 reporting 4.3.3.1 as netcdf library version

### ISSUE THREAD

**Issue by durack1** [Unidata/netcdf-c#121] opened 2015-07-09 01:23 UTC
The wrong version number is being reported by `ncdump` version `4.4.0-rc1`:
```
[durack1ml:150708_build/v4.4.0-rc1_install/bin] durack1% ncdump
ncdump [-c|-h] [-v ...] [[-b|-f] [c|f]] [-l len] [-n name] [-p n[,n]] [-k] [-x] [-s] [-t|-i] [-g ...] [-w] file
  [-c]             Coordinate variable data and header information
  [-h]             Header information only, no data
  [-v var1[,...]]  Data for variable(s) <var1>,... only
  [-b [c|f]]       Brief annotations for C or Fortran indices in data
  [-f [c|f]]       Full annotations for C or Fortran indices in data
  [-l len]         Line length maximum in data section (default 80)
  [-n name]        Name for netCDF (default derived from file name)
  [-p n[,n]]       Display floating-point values with less precision
  [-k]             Output kind of netCDF file
  [-s]             Output special (virtual) attributes
  [-t]             Output time data as date-time strings
  [-i]             Output time data as date-time strings with ISO-8601 'T' separator
  [-g grp1[,...]]  Data and metadata for group(s) <grp1>,... only
  [-w]             With client-side caching of variables for DAP URLs
  [-x]             Output XML (NcML) instead of CDL
  file             Name of netCDF file (or URL if DAP access enabled)
netcdf library version 4.3.3.1 of Jul  8 2015 18:15:19 $
```

**Comment by durack1** [comment] 2015-07-09 02:43
@WardF seems like this could be the problem:
https://github.com/Unidata/netcdf-c/blob/v4.4.0-rc1/configure#L594-595

**Comment by WardF** [comment] 2015-07-09 16:13
@durack1 Thanks for the heads up; I'm putting together the next release candidate and will make sure this is properly incremented!

**Comment by durack1** [comment] 2015-07-09 16:21
@WardF no problem, we've been having a couple of issues with accessing data through `dap` URLs, @doutriaux1 should be able to outline the problem better than me.. I'm fairly sure this remains an issue with the `4.4.0-rc1` release

**Comment by WardF** [comment] 2015-07-09 16:25
@durack @doutriaux1 That would be great if you can provide a bug report, as we hope to get the new release out in the next week or three and would try to include a fix for the issue, whatever it ends up being.

**Comment by doutriaux1** [comment] 2015-07-09 17:08
@WardF ok will do that.

**Comment by doutriaux1** [comment] 2015-07-09 17:45
@WardF @DennisHeimbigner see #122

**Comment by WardF** [comment] 2015-07-09 18:34
I'm closing this out since the issue is fixed; I was going to wait until I pushed out the release candidate later today, but issue #122 is going to delay that a little bit. So, I'll close this out now.

**Closed by WardF** 2015-07-09 18:34 UTC

**Comment by durack1** [comment] 2015-07-13 19:31
@WardF I can confirm that `ncdump 4.4.0-rc2` is now correctly reporting its version

**Comment by WardF** [comment] 2015-07-13 19:34
Great, thanks; the issue was pretty simple, I had not updated the string in `configure.ac` before generating `configure` and the associated files.  Thanks for keeping me on my toes!

**Comment by durack1** [comment] 2015-10-01 19:01
@WardF just wondering when you folks expect `4.4.0` to hit shelves (to be released)? From a quick scan of the [issues](https://github.com/Unidata/netcdf-c/issues) (there doesn't appear to be a `4.4.0` milestone configured) it seems there are still a couple to resolve before `4.4.0` is finalised?

**Comment by WardF** [comment] 2015-10-01 19:43
@durack1 I had planned on getting the 4.4.0-rc3 release out this week.  Our main feature for the 4.4.0 release is the inclusion of `cdf-5` support; you can view this on the `cdf-5` branch.  There is still a little cleaning up to do there, and to make sure everything works with the c++ and fortran interfaces.  I had hoped to get this done before releasing the next release candidate out the door, but I've delayed long enough, I feel.  I'm hoping to have the full 4.4.0 release within the month.

**Comment by durack1** [comment] 2015-10-01 21:49
@WardF ok great, I'll watch for the `rc3` release and take it for a run when it lands.. It'd certainly be nice to have `cdf-5` support too!
