### ISSUE TITLE
nc-config / pkg-config error with 4.4.0

### ISSUE THREAD

**Issue by sloede** [Unidata/netcdf-c#192] opened 2016-01-21 15:41 UTC
After installing netcdf 4.4.0, `nc-config` does not work as expected. If I run
```
nc-config --libs
```
I get the following output:
```
Package netcdf was not found in the pkg-config search path.
Perhaps you should add the directory containing `netcdf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'netcdf' found
```

Naively trying to fix this by setting `PKG_CONFIG_PATH` does not help either:
```
mic@aia256:/pds/opt/netcdf-4.4.0> ls /pds/opt/netcdf-4.4.0/lib64/pkgconfig
netcdf.pc
mic@aia256:/pds/opt/netcdf-4.4.0> export PKG_CONFIG_PATH=/pds/opt/netcdf-4.4.0/lib64/pkgconfig
mic@aia256:/pds/opt/netcdf-4.4.0> bin/nc-config --libs
Package netcdf was not found in the pkg-config search path.
Perhaps you should add the directory containing `netcdf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'netcdf' found
```

Any ideas what I did wrong?

**Comment by WardF** [comment] 2016-01-21 17:18
Thanks for the bug report; I've also been following the conversation over at `netcdf4-python`.  I'll try to recreate and diagnose this issue ASAP.

**Comment by pcm32** [comment] 2016-02-08 10:22
Hi there, we also get this same issue when trying install mzR R package, which requires NetCDF (which we installed locally, setting the prefix variable).

```
gcc -std=gnu99 -I/homes/user/software/R-3.2.3/include -DNDEBUG -D_LARGEFILE_SOURCE -I./boost_aux/ -I. -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5 -I./boost `nc-config --cflags || /bin/true` -I/usr/local/include -I"/nfs/gns/homes/user/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/nfs/gns/homes/user/software/R-3.2.3/library/zlibbioc/include"   -fpic  -g -O2  -c R_init_mzR.c -o R_init_mzR.o
Package netcdf was not found in the pkg-config search path.
Perhaps you should add the directory containing `netcdf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'netcdf' found
```

Interstingly, `nc-config --all` works fine:
```
This netCDF 4.4.0 has been built with the following features:

 --cc        -> gcc
 --cflags    ->  -I/homes/user/software/netcdf-4.4.0/include 
 --libs      ->

 --has-c++   -> no
 --cxx       -> 
 --has-c++4  -> no
 --cxx4      ->

 --fc        -> 
 --fflags    -> 
 --flibs     -> 
 --has-f90   -> no

 --has-dap   -> yes
 --has-nc2   -> yes
 --has-nc4   -> yes
 --has-hdf5  -> yes
 --has-hdf4  -> no
 --has-pnetcdf-> no

 --prefix    -> /homes/user/software/netcdf-4.4.0
 --includedir-> /homes/user/software/netcdf-4.4.0/include
 --version   -> netCDF 4.4.0
```

In this environment, the user doesn't have root access, so it requires local installs. Needless to say that we updated the PKG_CONFIG_PATH to point to where the .pc file is, with no results as described. This is on RHEL.

Many thanks!
Pablo

**Comment by WardF** [comment] 2016-02-22 18:20
I'm reviewing this issue and am unable to recreate the problem, currently; does the issue still occur on your end?  @pcm32, are you using `pkgconfig` or `nc-config`, just to clarify?  I've tested this with both `cmake` and `autotool`-based builds (on Ubuntu, admittedly, not RHEL.  I don't have access to a modern RHEL system), and have not encountered an issue.

**Comment by pcm32** [comment] 2016-02-23 16:43
Thanks for looking into this @WardF. On our side, the issue comes when using nc-config (when R invokes it to compile a package that requires NetCDF), or at least that is what I understand of the invoked line before the error comes up (see my first post, there is a part where `nc-config --cflags` is invoked in backticks). When we tried it it was the latest version of NetCDF available on the official web page (4.4.0). Is there a newer version that we should try?

I'll try to see if the issue comes up on Centos (6.7, as we see the issue on RHEL 6.6) and report back.

**Comment by WardF** [comment] 2016-02-23 17:46
I'll build a Centos 6.7 VM on my end and will see if I can recreate the issue there as well. Thanks!  I'd prefer to recreate and fix this issue if at all possible.

**Comment by pcm32** [comment] 2016-02-23 17:48
Ok, currently trying with Centos 6.6 cloud image:
http://cloud.centos.org/centos/6.6/images/CentOS-6-x86_64-GenericCloud.qcow2

Had to install some developers tools:
sudo yum groupinstall "Development Tools" -y && sudo yum install kernel-devel -y

And then installed zlib, HDF5 and now NetCDF C 4.4.0.

**Comment by pcm32** [comment] 2016-02-23 17:55
Ok, on Centos 6.6 with all manually installed following netcdf instructions, the call:

``
nc-config --libs
``

is now working... I'll try and see if the error from the R compilation still occurs.

**Comment by WardF** [comment] 2016-03-02 16:45
@pcm32 is the error still occurring? Unless I hear back to the contrary, I'm going to close this issue out as resolved in the near future :).

**Comment by pcm32** [comment] 2016-03-03 14:10
sorry, I was away for some days and have a bad backlog now. I couldn't reproduce it outright last time I tried it on a clean VM, so someone else in our group was going to retry the whole process on the original machine (now being very careful of following the same steps I did on the VM), but haven't heard back from this person. Please give me a few days to look into this again and I'll come back to you. Sorry about the delay.

**Comment by WardF** [comment] 2016-03-03 17:54
No problem at all; if it's resolved I want to close out the issue, but I don't want to do so prematurely.

**Comment by WardF** [comment] 2016-03-10 21:48
No problem, it's worth reviewing.  I'm glad to hear it's been resolved, I'll close out the issue.  Thanks for following up!

**Closed by WardF** 2016-03-10 21:48 UTC
Labels: area/build/all, status/under review
