### ISSUE TITLE
netcdf-4.4.1 tarball missing nc_test4/tst_fill_attr_vanish.c

### ISSUE THREAD

**Issue by gsjaardema** [Unidata/netcdf-c#281] opened 2016-06-30 14:20 UTC
File is mentioned in nc_test4/CMakelists.txt, but source file does not exist in the tar ball.

**Comment by WardF** [comment] 2016-06-30 16:55
Super. Thanks for reporting this, now I need to figure out why make distcheck didn't catch this.  Most likely I neglected to wire `tst_fill_attr_vanish.c` into the autoconf tests.  Clearly there are still holes in our 'is everything ready for a release' script.

Thanks!

**Comment by WardF** [comment] 2016-06-30 18:12
We will probably put out a new service release, 4.4.1.1, tomorrow or next Tuesday, to address this.

**Comment by WardF** [comment] 2016-07-06 20:23
The 4.4.1.1 release is delayed until we address some other things, and the issue is fixed so closing this out.

**Closed by WardF** 2016-07-06 20:23 UTC
Labels: type/bug
