### ISSUE TITLE
nc_set_fill doesn't work?

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf-c#131] opened 2015-10-06 21:33 UTC
Turning off variable pre-filling doesn't seem to work.  Here's an example:

    #include <stdlib.h>
    #include <stdio.h>
    #include <netcdf.h>
    static int total_err = 0, err = 0;
    #define NDIMS 1
    #define FILE_NAME "test.nc"
    #define DIM_LEN 2
    #define VAR_NAME "var"
    #define DIM_NAME "dim"
    /* This macro prints an error message with line number */
    #define ERR do { \
            fflush(stdout); /* Make sure our stdout is synced with stderr. */ \
            err++; \
            fprintf(stderr, "Sorry! Unexpected result, %s, line: %d\n", \
                                __FILE__, __LINE__);                                \
            return 2;                                                   \
    } while (0)

    int main()
    {
      int dimids[NDIMS];
      int varid, ncid;
      int no_fill, old_fill_mode;

      /* Create a file and set the fill mode */
      if (nc_create(FILE_NAME, NC_NETCDF4, &ncid)) ERR;
      if (nc_set_fill(ncid, NC_NOFILL, &old_fill_mode)) ERR;
      if (nc_def_dim(ncid, DIM_NAME, DIM_LEN, &dimids[0])) ERR;
      if (nc_def_var(ncid, VAR_NAME, NC_USHORT, NDIMS, dimids,
            &varid)) ERR;
      /* if (nc_def_var_fill(ncid, varid, 1, NULL)) ERR; */
      if (nc_close(ncid)) ERR;

      /* Open the file and check the fill mode */
      if (nc_open(FILE_NAME, NC_NOWRITE, &ncid)) ERR;
      if (nc_inq_var_fill(ncid, varid, &no_fill, NULL)) ERR;
      if (!no_fill) ERR;
      if (nc_close(ncid)) ERR;
    };

Running this program produces:

    Sorry! Unexpected result, test_fill.c, line: 40

If I comment out the ``nc_set_fill`` call and uncomment the ``nc_def_var_fill`` call, it works.

**Comment by WardF** [comment] 2015-10-06 21:36
Great timing, I was nearly ready for the next release candidate! :).  I'll take a look at this.

**Comment by WardF** [comment] 2015-10-06 22:08
This does appear to be a bug; the file is written out properly at least.  I'll continue to debug this and see what I can sort out; I'll also try to figure out when this bug was introduced.  More updates as the issue warrants.

**Comment by WardF** [comment] 2015-10-07 15:50
I've confirmed that the file is being written out properly.  Also, looking at existing tests, this test @jswhit has provided differs in that the file has been closed and reopened.

I've created a JIRA issue: https://bugtracking.unidata.ucar.edu/browse/NCF-342 and will update in both locations as events warrant.  I will create a branch for debugging this, which I expect with be named along the lines of 'ncf342' or some such; it should be self-evident.

**Comment by WardF** [comment] 2015-10-07 18:28
After a chance discussion with @russrew, I'm going to change the tags on this issue and close it out.  The reason being that this is expected behavior, and `NO_FILL` is a transient property on an *open* file.   This behavior apparently goes back to the very early versions of netCDF and was a design decision.  

I will try to bring this to the forefront in the documentation.  We have a documentation reorganization pending the full release of `4.4.0`.

**Closed** 2015-10-07 18:29 UTC
Labels: area/general, reason/expected behavior, resolution/ignore, type/bug

**Comment by jswhit** [comment] 2015-10-07 18:57
so does that mean when the file is closed and reopened, the data is filled with the default _FillValue?  Or just that any new variables that are created will be filled?

**Comment by WardF** [comment] 2015-10-07 19:13
New variables that are created *after* the file is closed and then re-opened will be filled unless `NC_NOFILL` is set again, because the no-fill state was not preserved in the file.   Existing data will not be filled with the default `_FillValue`, because from a programatic standpoint, it is impossible to tell which extant data is "real" and which is "garbage" resulting from the use of `NC_NOFILL`.
