### ISSUE TITLE
Netcdf-fortran-4.4.4 Parallel IO, MPI_COMM_WORLD

### ISSUE THREAD

**Issue by cyltby** [Unidata/netcdf-c#342] opened 2016-12-20 02:50 UTC
### Environment Information
Ubuntu14.04LTS; Intel compiler 15.0.0; mpich3.2; zlib-1.2.6;hdf5-1.8.18;netcdf-4.4.1.1;netcdf-fortran-4.4.4

Issue:
When compile the  file 'simple_xy_par_wr.f90' , it  throws the following problem. Is the problem caused by MPI ?

mpif90 -o xxx test.f90  -I /sat0/Public/soft_install/netcdf4.2/include  -L /sat0/Public/soft_install/netcdf4.2/lib  -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -lm -lz
--------------------------------------------------------------------------------------------------------------------------
test.f90(49): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [COMM]
       comm = MPI_COMM_WORLD, info = MPI_INFO_NULL))
-------^
test.f90(49): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [INFO]
       comm = MPI_COMM_WORLD, info = MPI_INFO_NULL))
------------------------------^
compilation aborted for test.f90 (code 1)
-------------------------------------------------------------------------------------------------------------------------------

Thanks.
Yong

**Comment by WardF** [comment] 2016-12-21 19:46
I believe the issue is related to the intel compiler.  That is only speculation on my part, but using openmpi and gcc, I can invoke `mpif90` in the same fashion as you outline above without error.

**Comment by cyltby** [comment] 2016-12-23 06:35
When not use these two option "comm = MPI_COMM_WORLD, info = MPI_INFO_NULL",  it seems to work fine.
----------------------------------------------------------------------------------------------------------------------------
call check(nf90_create(FILE_NAME, IOR(NF90_NETCDF4, NF90_MPIIO), ncid, &
      comm = MPI_COMM_WORLD, info = MPI_INFO_NULL))
------------------------------------------------------------------------------------------------------------------------------
You are right. It is the intel compiler that cause the problem.  I will do a test with openmpi and gcc, but it got an error when compile hdf5 with gcc.

Thanks.
-Yong

**Comment by edwardhartnett** [comment] 2019-12-19 15:30
This issue can be closed. The fortran library is working well with parallel I/O and is tested as such in my Jenkins CI system.

**Comment by WardF** [comment] 2019-12-19 16:23
I'll close this out but we'll need to open another one here shortly (as soon as I have the bandwidth), as I'm seeing failures with Fortran and Parallel I/O on our internal non-HPC parallel systems.  I'll have full details in the new issue but it relates to `configure` not being able to find MPI_File_open.

**Closed by WardF** 2019-12-19 16:23 UTC

**Comment by edwardhartnett** [comment] 2019-12-19 16:54
Well hopefully nothing too bad as all of my parallel CI runs for netcdf-fortran are working, including with current master of netcdf-c and netcdf-fortran.
