### ISSUE TITLE
netCDF writes string (unicode) attributes in HDF5 files as 1-d arrays, not scalars

### ISSUE THREAD

**Issue by shoyer** [Unidata/netcdf-c#127] opened 2015-08-20 17:27 UTC
See this netCDF4-Python issue for more details:
https://github.com/Unidata/netcdf4-python/issues/448

But basically, if we write a string attribute to a netCDF4 file with `nc_put_att_string`, we get an HDF5 file that looks like this:
```
$ h5dump /Users/shoyer/Downloads/global-attr.nc
HDF5 "/Users/shoyer/Downloads/global-attr.nc" {
GROUP "/" {
   ATTRIBUTE "units" {
      DATATYPE  H5T_STRING {
         STRSIZE H5T_VARIABLE;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): "days since 1900"
      }
   }
}
}
```

`DATASPACE SIMPLE` indicates that this is an array (of one element). What I think we really want is a scalar value `DATASPACE  SCALAR`.

It's also strange that we have `CSET H5T_CSET_ASCII`. I think we really want `CSET H5T_CSET_UTF8`.

cc @jswhit

**Comment by WardF** [comment] 2015-08-20 18:26
Thanks for the report; I'm going to tentatively^1 mark this as a bug and will open a ticket to get it fixed.  I'll follow up here with a link and any pertinent information. 

1: Unless it turns out there was a specific reason for this that I'm currently unaware of, in which case I'll also follow up here.

**Comment by WardF** [comment] 2015-08-20 18:30
One question that occurs to me is if this has come about because of a change in the HDF5 API; for example, if the current code is appropriate up until HDF5 version X.  This is important because it may result in bumping the minimum required version of hdf5.

**Comment by DennisHeimbigner** [comment] 2015-08-20 19:52
The ascii instead of utf8 is definitely a bug.
The vector vs scalar issue may not be. Remember
that attributes can be vectors of values.
=Dennis Heimbigner


Ward Fisher wrote:

**Comment by DennisHeimbigner** [comment] 2015-08-20 20:21
Ok, I have a tentative fix for the UTF-8 issue.
I can see how to change to use scalar for a single element attribute,
but it will take a bit of work to implement it. Is this change really necessary?

**Comment by shoyer** [comment] 2015-08-20 20:43
My h5netcdf tries to read netCDF4 files using h5py and its own implementation of the netCDF4 spec:
https://github.com/shoyer/h5netcdf

h5py wraps HDF5 pretty directly, so when I try to retrieve my unicode attributes, I get back something like this in Python:
`array([b'days since 1900'], dtype=object)`

This is a 1D array of variable length ASCII strings (the Python bytes type `b`), which seems like a faithful reading of the HDF5 file. Unfortunately, 1D arrays aren't always interchangeable with scalars, at least not directly (e.g., consider a `units` attribute).

Of course, this stuff is straightforward to work around, but in the interest of cross-compatibility between netCDF4 and HDF5, I think it would be a good idea to write unicode strings as scalars. `nc_put_att_text`, for example, already writes scalar values.

**Comment by DennisHeimbigner** [comment] 2015-08-20 20:54
The problem appears to be in the definition of attribute.
In netcdf-4 (as opposed to HDF5) all attributes are potentially
vectors. Is it the case that h5py assumes all attributes are scalar?
=Dennis Heimbigner
  Unidata

Stephan Hoyer wrote:

**Comment by shoyer** [comment] 2015-08-20 21:43
h5py writes both scalar and array valued attributes, depending on the shape of the input. I think we basically want the same thing for netCDF4:
```
In [23]: f = h5py.File('/Users/shoyer/Downloads/demo-attributes.h5')

In [24]: f.attrs['unicode_scalar'] = u'foo'

In [25]: f.attrs['bytes_scalar'] = b'foo'

In [26]: dt = h5py.special_dtype(vlen=unicode)

In [27]: f.attrs.create('unicode_array', [u'foo', u'bar'], dtype=dt)

In [28]: f.attrs['bytes_array'] = ['foo', 'bar']

In [29]: dict(f.attrs)
Out[29]:
{u'bytes_array': array(['foo', 'bar'],
       dtype='|S3'),
 u'bytes_scalar': 'foo',
 u'unicode_array': array([u'foo', u'bar'], dtype=object),
 u'unicode_scalar': u'foo'}

In [30]: f.close()
```

**Comment by russrew** [comment] 2015-08-25 19:33
This seems like a reasonable request, especially given that nc_att_put_text() already writes strings as scalar values (which I didn't know but confirmed). So it seems nc_att_put_string() could do the same. There would be a backward compatibility issue, in that the netCDF-C library would have to be able to read either scalar or length-one vector strings through nc_att_get_string(), in order to be able to read string attributes from existing archives, but apparently nc_att_get_text() already reads scalar-valued strings.

However, permitting netCDF-4 attributes to be multidimensional with rank >1 (as HDF5 does) seems like too big a change, and one no one has requested. Attributes are intentionally simpler than variables, they are not just small variables. The differences between attributes and variables are important in making it easy for users and data providers to decide which way to represent metadata and data in the netCDF-4 data model.

**Comment by shoyer** [comment] 2015-08-31 21:55
> However, permitting netCDF-4 attributes to be multidimensional with rank >1 (as HDF5 does) seems like too big a change, and one no one has requested.

Well, now that you mention it, I would like to request this change, though it's not a big deal :). From my perspective as an array-oriented programmer, if arrays are permitted, I would expect any rank to be OK. This isn't strictly necessary, but it's a useful feature and I don't see a good reason for going out of our way to prohibit it. This is especially unexpected given that it's not a documented difference between HDF5 and netCDF4...

**Comment by WardF** [comment] 2015-10-01 19:35
Closing this out as the utf8/ascii issue is resolved.  Will put the other request and information in a separate issue!

**Closed by WardF** 2015-10-01 19:35 UTC
Labels: bug

**Comment by shoyer** [comment] 2015-10-19 22:04
Thanks @WardF. Will this be in the final 4.4.0 release?

**Comment by WardF** [comment] 2015-10-20 15:41
It will, and the parts implemented should be in the recent RC3 release as well!

-Ward

**Comment by shoyer** [comment] 2015-10-20 16:10
Great, thanks.

**Comment by shoyer** [comment] 2017-04-07 03:52
@WardF Did you ever open that follow-up issue on scalar vs array types for string attributes? Someone brought this up again on the h5netcdf issue tracker (https://github.com/shoyer/h5netcdf/issues/27).

**Comment by DennisHeimbigner** [comment] 2017-04-07 19:08
I thought we decided that the netcdf-4 spec required all attributes to be treated
as a vector of values, even if it one element. I think that if python code wants something
else, it is up to it to deal with it.
